extends: stylelint-config-silverwind

rules:
  "@stylistic/indentation": null
  block-no-empty: null
  declaration-property-value-no-unknown: null
  scale-unlimited/declaration-strict-value: null
  selector-attribute-quotes: null
  selector-no-vendor-prefix: null
  no-duplicate-selectors: null
  at-rule-no-vendor-prefix: null
